id: I6EF98FF3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T14:43:24+00:00'
last_modified: '2022-06-07T21:16:44.046865+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016242
  title: སྒོ་མང་གྲྭ་ཚང་བཅས་ཀྱི་ཚོགས་འདོན་ཆོས་སྤྱོད་ཀྱི་རིམ་པ་བསྐལ་བཟང་མགྲིན་རྒྱན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9584':
      image_group_id: I00JW501115
      title: ''
      total_pages: 234
      order: 1
      base_file: 9584.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
