id: P004233
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:03:28.876004
source_metadata:
  id: bdr:W00EGS1016242
  title: སྒོ་མང་གྲྭ་ཚང་བཅས་ཀྱི་ཚོགས་འདོན་ཆོས་སྤྱོད་ཀྱི་རིམ་པ་བསྐལ་བཟང་མགྲིན་རྒྱན
  author: ''
  volumes:
    72985e94850e4cc38f0050378288220c:
      image_group_id: I00JW501115
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
